PanelBundle\Entity\Usuario:
    type: entity
    table: null
    repositoryClass: PanelBundle\Repository\UsuarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        pass:
            type: text
        createdAt:
            type: date
            column: created_at
        updatedAt:
            type: date
            column: updated_at
        rol:
            type: string
            length: 255
            nullable: true
        lastSession:
            type: date
            column: last_session
    lifecycleCallbacks: {  }
