<?php

namespace PanelBundle\Repository;

/**
 * exceldataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class exceldataRepository extends \Doctrine\ORM\EntityRepository
{
}
