<?php

namespace PanelBundle\Repository;

/**
 * excelDataBaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class excelDataBaseRepository extends \Doctrine\ORM\EntityRepository
{
}
